# Generated by Django 4.1.5 on 2023-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('residential_address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('date_admitted', models.DateField()),
                ('ward', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('symptoms', models.TextField()),
            ],
        ),
    ]
